backend:
  name: github
  repo: Axiomatic47/corporate-veil
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "composition/{{fields.collection_type}}/section/{{fields.section}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: ["memorandum", "corrective"],
          required: true
        }
      - { 
          label: "Section",
          name: "section",
          widget: "number",
          default: 1,
          required: true,
          min: 1
        }
      - { label: "Content", name: "body", widget: "markdown" }
    sortable_fields:
      - title
      - description
      - section
    view_filters:
      - label: "Memorandum"
        field: collection_type
        pattern: "memorandum"
      - label: "Corrective"
        field: collection_type
        pattern: "corrective"
    view_groups:
      - label: "By Collection Type"
        field: collection_type
      - label: "By Section"
        field: section