backend:
  name: github
  repo: axiomaticjk/corporate-veil-main
  branch: main

local_backend: true
local_backend_url: http://localhost:8081/api/v1

media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: "simple"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    identifier_field: "title"
    format: "frontmatter"
    sort: "section"
    preview_path: compositions/{{slug}}
    editor:
      preview: true
    fields:
      - {label: "Collection Type", name: "collection_type", widget: "select", options: ["memorandum", "corrective"]}
      - {label: "Section", name: "section", widget: "number", value_type: "int", default: 1}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Content (Level 1)", name: "content_level_1", widget: "markdown"}
      - {label: "Content (Level 3)", name: "content_level_3", widget: "markdown"}
      - {label: "Content (Level 5)", name: "content_level_5", widget: "markdown"}