backend:
  name: git-gateway
  branch: main
  proxy_url: http://localhost:8082/api/v1

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: "simple"

editor:
  preview: false

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    identifier_field: "title"
    format: "frontmatter"
    sort: "section"
    fields:
      - {label: "Collection Type", name: "collection_type", widget: "select", options: ["memorandum", "corrective"]}
      - {label: "Section", name: "section", widget: "number", value_type: "int", default: 1}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Content (Level 1)", name: "content_level_1", widget: "markdown"}
      - {label: "Content (Level 3)", name: "content_level_3", widget: "markdown"}
      - {label: "Content (Level 5)", name: "content_level_5", widget: "markdown"}