backend:
  name: github
  repo: axiomatic47/corporate-veil
  branch: main
  auth_type: oauth
  app_id: Ov23liAKv2NEFlD8awLo
  client_secret: d9fa24182db927e76e66978eea1a3dbfb081ee40

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: simple

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: ["memorandum", "corrective"],
          required: true
        }
      - { label: "Section", name: "section", widget: "number", default: 1 }
      - { label: "Content", name: "body", widget: "markdown" }
    sortable_fields:
      - title
      - description
    view_filters:
      - label: "Memorandum"
        field: collection_type
        pattern: "memorandum"
      - label: "Corrective"
        field: collection_type
        pattern: "corrective"

slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"