backend:
  name: git-gateway
  branch: main
  local_backend: true
  local_backend_url: http://localhost:8082/api/v1

media_folder: "public/uploads"
public_folder: "/uploads"

# Enable real-time preview and local backend
local_backend: true
publish_mode: editorial_workflow

collections:
  - name: "memorandum"
    label: "Memorandum Compositions"
    folder: "content/memorandum"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }
      
  - name: "corrective"
    label: "Corrective Compositions"
    folder: "content/corrective"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }