backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    format: "frontmatter"
    extension: "md"
    identifier_field: "title"
    fields:
      - { 
          label: "Title", 
          name: "title", 
          widget: "string",
          required: true,
          hint: "Enter the main title of the composition"
        }
      - { 
          label: "Description", 
          name: "description", 
          widget: "text",
          required: true,
          hint: "Brief description of the composition's purpose" 
        }
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: ["memorandum", "corrective"],
          required: true,
          hint: "Select whether this is a Memorandum or Corrective composition"
        }
      - {
          label: "Reading Level",
          name: "reading_level",
          widget: "select",
          options: ["1", "3", "5"],
          default: "3",
          required: true,
          hint: "Select the reading comprehension level (1=Basic, 3=Intermediate, 5=Advanced)"
        }
      - { 
          label: "Section",
          name: "section",
          widget: "number",
          default: 1,
          required: true,
          hint: "Numerical order of this section within the composition"
        }
      - { 
          label: "Content Level 1", 
          name: "content_level_1", 
          widget: "markdown",
          required: true,
          hint: "Basic reading level content (Level 1)"
        }
      - { 
          label: "Content Level 3", 
          name: "content_level_3", 
          widget: "markdown",
          required: true,
          hint: "Intermediate reading level content (Level 3)"
        }
      - { 
          label: "Content Level 5", 
          name: "content_level_5", 
          widget: "markdown",
          required: true,
          hint: "Advanced reading level content (Level 5)"
        }
      - { 
          label: "Section Title Level 1", 
          name: "title_level_1", 
          widget: "string",
          required: true,
          hint: "Section title for basic reading level (Level 1)"
        }
      - { 
          label: "Section Title Level 3", 
          name: "title_level_3", 
          widget: "string",
          required: true,
          hint: "Section title for intermediate reading level (Level 3)"
        }
      - { 
          label: "Section Title Level 5", 
          name: "title_level_5", 
          widget: "string",
          required: true,
          hint: "Section title for advanced reading level (Level 5)"
        }
    view_filters:
      - label: "Memorandum"
        field: collection_type
        pattern: "memorandum"
      - label: "Corrective"
        field: collection_type
        pattern: "corrective"
      - label: "Reading Level 1"
        field: reading_level
        pattern: "1"
      - label: "Reading Level 3"
        field: reading_level
        pattern: "3"
      - label: "Reading Level 5"
        field: reading_level
        pattern: "5"