backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    format: "frontmatter"
    extension: "md"
    identifier_field: "title"
    fields:
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: [
            { label: "Memorandum", value: "memorandum" },
            { label: "Corrective", value: "corrective" }
          ],
          required: true
        }
      - {
          label: "Section",
          name: "section",
          widget: "hidden",
          default: 1
        }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          required: true
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true
        }
      - {
          label: "Content Level 1",
          name: "content_level_1",
          widget: "markdown",
          required: true
        }
      - {
          label: "Content Level 3",
          name: "content_level_3",
          widget: "markdown",
          required: true
        }
      - {
          label: "Content Level 5",
          name: "content_level_5",
          widget: "markdown",
          required: true
        }