backend:
  name: github
  repo: Axiomatic47/corporate-veil
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    format: "frontmatter"
    extension: "md"
    identifier_field: "title"
    fields:
      - { 
          label: "Title", 
          name: "title", 
          widget: "string",
          required: true
        }
      - { 
          label: "Description", 
          name: "description", 
          widget: "text",
          required: true 
        }
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: ["memorandum", "corrective"],
          required: true
        }
      - {
          label: "Reading Level",
          name: "reading_level",
          widget: "select",
          options: [1, 3, 5],
          default: 3,
          required: true
        }
      - { 
          label: "Section",
          name: "section",
          widget: "number",
          default: 1,
          required: true
        }
      - { 
          label: "Content Level 1", 
          name: "content_level_1", 
          widget: "markdown",
          required: true 
        }
      - { 
          label: "Content Level 3", 
          name: "content_level_3", 
          widget: "markdown",
          required: true 
        }
      - { 
          label: "Content Level 5", 
          name: "content_level_5", 
          widget: "markdown",
          required: true 
        }
      - { 
          label: "Section Title Level 1", 
          name: "title_level_1", 
          widget: "string",
          required: true 
        }
      - { 
          label: "Section Title Level 3", 
          name: "title_level_3", 
          widget: "string",
          required: true 
        }
      - { 
          label: "Section Title Level 5", 
          name: "title_level_5", 
          widget: "string",
          required: true 
        }
    sortable_fields: ["title", "section", "reading_level"]
    view_filters:
      - label: "Memorandum"
        field: collection_type
        pattern: "memorandum"
      - label: "Corrective"
        field: collection_type
        pattern: "corrective"
      - label: "Reading Level 1"
        field: reading_level
        pattern: 1
      - label: "Reading Level 3"
        field: reading_level
        pattern: 3
      - label: "Reading Level 5"
        field: reading_level
        pattern: 5