backend:
  name: github
  repo: Axiomatic47/corporate-veil
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    format: "frontmatter"
    extension: "md"
    identifier_field: "title"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}-section-{{section}}"
    fields:
      - { 
          label: "Title", 
          name: "title", 
          widget: "string",
          required: true
        }
      - { 
          label: "Description", 
          name: "description", 
          widget: "text",
          required: true 
        }
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: ["memorandum", "corrective"],
          required: true
        }
      - { 
          label: "Section",
          name: "section",
          widget: "number",
          default: 1,
          value_type: "int",
          min: 1,
          required: true
        }
      - { 
          label: "Content", 
          name: "body", 
          widget: "markdown",
          required: true 
        }
    sortable_fields: ["title", "section"]
    view_filters:
      - label: "Memorandum"
        field: collection_type
        pattern: "memorandum"
      - label: "Corrective"
        field: collection_type
        pattern: "corrective"