backend:
  name: github
  repo: axiomaticjk/corporate-veil-main
  branch: main
  base_url: http://localhost:8080

local_backend: true
local_backend_url: http://localhost:8081/api/v1

media_folder: "public/uploads"
public_folder: "/uploads"
format: "json"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    extension: "json"
    slug: "{{collection_type}}-{{slug}}"
    preview_path: "composition/{{collection_type}}/section/1"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Type", name: "collection_type", widget: "select", options: ["memorandum", "corrective"]}
      - label: "Sections"
        name: "sections"
        widget: "list"
        allow_add: true
        label_singular: "Section"
        summary: "{{fields.title}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Basic Content (Level 1)", name: "content_level_1", widget: "markdown"}
          - {label: "Intermediate Content (Level 3)", name: "content_level_3", widget: "markdown"}
          - {label: "Advanced Content (Level 5)", name: "content_level_5", widget: "markdown"}