backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    format: "frontmatter"
    extension: "md"
    identifier_field: "title"
    fields:
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: [
            { label: "Memorandum", value: "memorandum" },
            { label: "Corrective", value: "corrective" }
          ],
          required: true
        }
      - {
          label: "Section Number",
          name: "section",
          widget: "number",
          value_type: "int",
          min: 1,
          required: true
        }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          required: true
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true
        }
      - {
          label: "Content",
          name: "content",
          widget: "markdown",
          required: true
        }