backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: "simple"

editor:
  preview: false

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    identifier_field: "title"
    format: "frontmatter"
    sortable_fields: ['section']
    view_filters:
      - label: "Memorandum"
        field: collection_type
        pattern: "memorandum"
      - label: "Corrective"
        field: collection_type
        pattern: "corrective"
    editor:
      preview: false
    fields:
      - {label: "Collection Type", name: "collection_type", widget: "select", options: ["memorandum", "corrective"]}
      - {label: "Section", name: "section", widget: "hidden", default: 1}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Content (Level 1)", name: "content_level_1", widget: "markdown"}
      - {label: "Content (Level 3)", name: "content_level_3", widget: "markdown"}
      - {label: "Content (Level 5)", name: "content_level_5", widget: "markdown"}

    widgets:
      - name: custom-sidebar
        collection: compositions