backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    format: "frontmatter"
    extension: "md"
    identifier_field: "title"
    sortable_fields: ['title', 'section']
    fields:
      - { 
          label: "Title", 
          name: "title", 
          widget: "string",
          required: true
        }
      - { 
          label: "Description", 
          name: "description", 
          widget: "text",
          required: true
        }
      - {
          label: "Collection Type",
          name: "collection_type",
          widget: "select",
          options: ["memorandum", "corrective"],
          required: true
        }
      - {
          label: "Reading Level",
          name: "reading_level",
          widget: "select",
          options: ["1", "3", "5"],
          default: "3",
          required: true
        }
      - { 
          label: "Section",
          name: "section",
          widget: "number",
          default: 1,
          required: true
        }
      - { 
          label: "Basic Level Title", 
          name: "title_level_1", 
          widget: "string",
          required: true
        }
      - { 
          label: "Basic Level Content", 
          name: "content_level_1", 
          widget: "markdown",
          required: true
        }
      - { 
          label: "Intermediate Level Title", 
          name: "title_level_3", 
          widget: "string",
          required: true
        }
      - { 
          label: "Intermediate Level Content", 
          name: "content_level_3", 
          widget: "markdown",
          required: true
        }
      - { 
          label: "Advanced Level Title", 
          name: "title_level_5", 
          widget: "string",
          required: true
        }
      - { 
          label: "Advanced Level Content", 
          name: "content_level_5", 
          widget: "markdown",
          required: true
        }
    view_filters:
      - label: "Memorandum"
        field: collection_type
        pattern: "memorandum"
      - label: "Corrective"
        field: collection_type
        pattern: "corrective"
    view_groups:
      - label: "Section"
        field: section
      - label: "Collection Type"
        field: collection_type